In [4]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import sklearn as sk
from sklearn.model_selection import train_test_split
eps=np.finfo(float).eps
from binarytree import tree,Node
from sklearn.metrics import classification_report, confusion_matrix ,accuracy_score
from sklearn.tree import DecisionTreeClassifier
from operator import itemgetter
import copy
import collections
from pylab import *
import matplotlib
import matplotlib.pyplot as plt

In [5]:
def euclidean_distance(x, y): 
#row by row i.e all features resultant euclid distance in single line
    return np.sqrt(np.sum((x - y) ** 2))


In [6]:
names=['sepal-length','sepal-width','petal-length','petal-width','Class']
df=pd.read_csv("Iris/Iris.csv",names=names)

In [7]:
X =df.drop(['Class'],axis=1)
y=df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
df=X_train
y_train=list(y_train)

In [9]:
def predict(Xtest,k):
    y_res=[]
    for index,row in X_test.iterrows():
        result=[]
        for index1,row1 in df.iterrows():
                result.append(euclidean_distance(row,row1))
        df1=pd.DataFrame(
        {
            'dist':result,
            'class':y_train
        })
        df1=df1.sort_values(by=['dist'])
        count=0;
#         k=5
        classVote={}
        max1=0
        res=""
        for index1,row1 in df1.iterrows():
            capital=row1['class']
            count=count+1
            if  capital in classVote:
                classVote[capital] = classVote[capital]+1
            else:
                classVote[capital]=1
            if classVote[capital]>=max1:
                res=capital
                max1=classVote[capital]
            if count==k:
                break;
        y_res.append(res)
    return y_res

In [10]:
y_res=predict(X_test,5)
print("------Confusion Matrix---------")
print(confusion_matrix(y_test, y_res))  
print(classification_report(y_test, y_res)) 
print("Accuracy:--"accuracy_score(y_test,y_res))


[[ 6  0  0]
 [ 0 12  1]
 [ 0  1  7]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       0.92      0.92      0.92        13
 Iris-virginica       0.88      0.88      0.88         8

      micro avg       0.93      0.93      0.93        27
      macro avg       0.93      0.93      0.93        27
   weighted avg       0.93      0.93      0.93        27

0.9259259259259259


In [11]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
# knn.score(X_train, y_test)
y_pred =knn.predict(X_test)  
print("------System confusion Matrix---------")
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 
print("System Accuracy")
print(accuracy_score(y_test,y_pred))

[[ 6  0  0]
 [ 0 12  1]
 [ 0  1  7]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       0.92      0.92      0.92        13
 Iris-virginica       0.88      0.88      0.88         8

      micro avg       0.93      0.93      0.93        27
      macro avg       0.93      0.93      0.93        27
   weighted avg       0.93      0.93      0.93        27

0.9259259259259259
